export enum EventAction {
  COMPONENT_CREATE = 'COMPONENT_CREATE',
  COMPONENT_MOUNT = 'COMPONENT_MOUNT',
  COMPONENT_REMOVE = 'COMPONENT_REMOVE',
  COMPONENT_UPDATE = 'COMPONENT_UPDATE',
  GET_RENDERER_COMPONENT = 'GET_RENDERER_COMPONENT',
}
